### ISSUE TITLE
FlairMax crashing while on song page

### ISSUE THREAD

**Issue by occune** [flairmax/FlairMax-Issues#4] opened 2023-04-18 06:35 UTC
Leaving FlairMax open on song page make it crash (perhaps has something to do with external streaming services when its trying to show external links (e.g. youtube)?)

FlairMax version 1.1.2.0 x86_64 OS Build 22621.1555

![ApplicationFrameHost_oMxzyGMLqo](https://user-images.githubusercontent.com/9035722/232691206-2ed3fd1f-6a42-4c31-8ff7-b6cfa8d26f86.png)

**Comment by ahmed605** [comment] 2023-04-18 11:49
thanks for reporting, will take a look at it

**Comment by ahmed605** [comment] 2023-04-21 18:33
I can't reproduce the issue locally (tried the same track), so I would need some more info
does it only happen on this track or all tracks?
also does it happen on a specific Core (like Shazam) or both Cores?

**Comment by occune** [comment] 2023-04-22 07:06
It does happen on all tracks and with all cores
It's not about the song identification, its about the FlairMax giving you the options to listen to the exact song on various streaming platforms (e.g. YouTube, Apple Music)
My guess is that FlairMax is unable to perform a HTTP request

**Comment by mediaexplorer74** [comment] 2023-04-22 07:27
> I can't reproduce the issue locally (tried the same track), so I would need some more info does it only happen on this track or all tracks? also does it happen on a specific Core (like Shazam) or both Cores?

Sorry to ping you but: where is main repo named FlairMax? FlairMax is not open-source?...

**Comment by ahmed605** [comment] 2023-04-22 08:36
> It does happen on all tracks and with all cores
> It's not about the song identification, its about the FlairMax giving you the options to listen to the exact song on various streaming platforms (e.g. YouTube, Apple Music)
> My guess is that FlairMax is unable to perform a HTTP request 

I see, will take a look at AppCenter logs and see if I can identify the issue from there

**Comment by ahmed605** [comment] 2023-04-22 08:37
> > I can't reproduce the issue locally (tried the same track), so I would need some more info does it only happen on this track or all tracks? also does it happen on a specific Core (like Shazam) or both Cores?
> 
> Sorry to ping you but: where is main repo named FlairMax? FlairMax is not open-source?...

FlairMax isn't open source **but** I'm preparing a repo called "FlairMax.OpenSource" (currently private) that will include parts of FlairMax's code that I think will be useful to other devs

**Comment by ahmed605** [comment] 2023-04-23 12:46
@occune found 2 issues in AppCenter logs that this issue must be one of them, one issue is the app failing to make http requests (it timeouts), and the other one is the app failing to save the track to the history file
So to narrow it down even more, can you check if tracks gets saved to the history (open the history page and see if they are there)?

**Comment by occune** [comment] 2023-04-24 08:15
I noticed a very weird behavior 
FlairMax is able to display external links for the freshly recognized track (no crashes, too)
But i am not able to select the freshly recognized track in the history (clicking on the track does nothing)
Still experiencing crashes with the older tracks (but i am able to click on them)

**Comment by ahmed605** [comment] 2023-04-24 10:48
> But i am not able to select the freshly recognized track in the history (clicking on the track does nothing)

I assume that you were using the ACRCloud Core to recognize these tracks? unfortunately not all tracks recognized by ACRCloud Core are clickable in history due to them not providing any way we can fetch track data back using the track id so we rely on hacks to be able to fetch the data for some tracks but unfortunately these hacks do not work for all tracks.

**Comment by occune** [comment] 2023-04-27 07:15
>So to narrow it down even more, can you check if tracks gets saved to the history (open the history page and see if they are there)?

Its still gets saved to the history with the Shazam Core enabled, but i am still experiencing crashes while FlairMax tries to perform the HTTP requests on the song page

**Comment by ahmed605** [comment] 2023-04-28 15:05
> > So to narrow it down even more, can you check if tracks gets saved to the history (open the history page and see if they are there)?
> 
> Its still gets saved to the history with the Shazam Core enabled, but i am still experiencing crashes while FlairMax tries to perform the HTTP requests on the song page

@occune can you check if this version fixes the http requests issue for you?
https://1drv.ms/u/s!AhRToRBIf45pgaUbamOObrCjm3Uwtg?e=MePFZc

**Comment by occune** [comment] 2023-04-28 15:57
![image](https://user-images.githubusercontent.com/9035722/235196176-d35c92a6-7eb2-4312-ae0e-ef9d21b2ed00.png)
It does

**Comment by ahmed605** [comment] 2023-04-28 16:03
Thanks for confirming that it works, I will leave the issue open for now until an update with the fix releases.

**Comment by ahmed605** [comment] 2023-05-17 10:16
Fixed as of v1.1.3.0

**Closed as completed by ahmed605** 2023-05-17 10:16 UTC
Labels: crash
